FROM put/rob1:lab6

RUN apt-get update && \
    apt-get install -y \
    ros-noetic-tf \
    ros-noetic-tf2-tools \
    ros-noetic-turtle-tf2 \
    ros-noetic-tf-conversions \
    mupdf

RUN ln -s /usr/bin/python3 /usr/bin/python
