FROM put/rob1:base

RUN apt install -y \
        ros-noetic-cv-camera \
        ros-noetic-usb-cam

# WORKDIR /catkin_ws

# RUN mkdir src && cd src && git clone https://github.com/dominikbelter/sensors_demos_gazebo

# RUN source /opt/ros/noetic/setup.bash && catkin_make

# WORKDIR /
